import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GeistSans } from 'geist/font/sans';
import './globals.css'
import { EdgeStoreProvider } from './lib/edgestore';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'FredFrameAgain',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <EdgeStoreProvider>{children}</EdgeStoreProvider>
      </body>
    </html>
  )
}
